package com.weixin.ssm.dao.mapper;

import com.weixin.ssm.model.entity.MxActivitiesMyspaceMaterial;
import com.weixin.ssm.model.entity.MxActivitiesMyspaceMaterialWithBLOBs;

public interface MxActivitiesMyspaceMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_material
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    int deleteByPrimaryKey(Integer material_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_material
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    int insert(MxActivitiesMyspaceMaterialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_material
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    int insertSelective(MxActivitiesMyspaceMaterialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_material
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    MxActivitiesMyspaceMaterialWithBLOBs selectByPrimaryKey(Integer material_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_material
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    int updateByPrimaryKeySelective(MxActivitiesMyspaceMaterialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_material
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MxActivitiesMyspaceMaterialWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_material
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    int updateByPrimaryKey(MxActivitiesMyspaceMaterial record);
}