package com.weixin.ssm.dao.mapper;

import com.weixin.ssm.model.entity.MxActivitiesMyspaceComment;
import com.weixin.ssm.model.entity.MxActivitiesMyspaceCommentWithBLOBs;

public interface MxActivitiesMyspaceCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_comment
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    int deleteByPrimaryKey(Integer comment_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_comment
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    int insert(MxActivitiesMyspaceCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_comment
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    int insertSelective(MxActivitiesMyspaceCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_comment
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    MxActivitiesMyspaceCommentWithBLOBs selectByPrimaryKey(Integer comment_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_comment
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    int updateByPrimaryKeySelective(MxActivitiesMyspaceCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_comment
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MxActivitiesMyspaceCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_comment
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    int updateByPrimaryKey(MxActivitiesMyspaceComment record);
}