package com.weixin.ssm.dao.mapper;

import com.weixin.ssm.model.entity.MxActivitiesMyspaceData;

public interface MxActivitiesMyspaceDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_data
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    int deleteByPrimaryKey(Integer myspace_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_data
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    int insert(MxActivitiesMyspaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_data
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    int insertSelective(MxActivitiesMyspaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_data
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    MxActivitiesMyspaceData selectByPrimaryKey(Integer myspace_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_data
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    int updateByPrimaryKeySelective(MxActivitiesMyspaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_data
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    int updateByPrimaryKey(MxActivitiesMyspaceData record);
}