package com.weixin.ssm.dao.mapper;

import com.weixin.ssm.model.entity.MxActivitiesMyspaceUsers;

public interface MxActivitiesMyspaceUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_users
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_users
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    int insert(MxActivitiesMyspaceUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_users
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    int insertSelective(MxActivitiesMyspaceUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_users
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    MxActivitiesMyspaceUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_users
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    int updateByPrimaryKeySelective(MxActivitiesMyspaceUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_activities_myspace_users
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    int updateByPrimaryKey(MxActivitiesMyspaceUsers record);
}