package com.weixin.ssm.dao.mapper;

import com.weixin.ssm.model.entity.MxUsersData;
import com.weixin.ssm.model.entity.MxUsersDataWithBLOBs;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MxUsersDataMapper {

    List<MxUsersData> selectAllUsers();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_users_data
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    int deleteByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_users_data
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    int insert(MxUsersDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_users_data
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    int insertSelective(MxUsersDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_users_data
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    MxUsersDataWithBLOBs selectByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_users_data
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    int updateByPrimaryKeySelective(MxUsersDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_users_data
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MxUsersDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_users_data
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    int updateByPrimaryKey(MxUsersData record);
}