package com.weixin.ssm.model.entity;

import java.util.Date;

public class MxActivitiesMyspaceData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private Integer myspace_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.activities_id
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private Integer activities_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.describe
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.create_date
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.Update_date
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private Date update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.others
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.upperLimit
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private Integer upperLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.lowerLimit
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private Integer lowerLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.state
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.cover_image_url
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private String cover_image_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_data.myspace_name
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    private String myspace_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.myspace_id
     *
     * @return the value of mx_activities_myspace_data.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public Integer getMyspace_id() {
        return myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.myspace_id
     *
     * @param myspace_id the value for mx_activities_myspace_data.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setMyspace_id(Integer myspace_id) {
        this.myspace_id = myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.activities_id
     *
     * @return the value of mx_activities_myspace_data.activities_id
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public Integer getActivities_id() {
        return activities_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.activities_id
     *
     * @param activities_id the value for mx_activities_myspace_data.activities_id
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setActivities_id(Integer activities_id) {
        this.activities_id = activities_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.describe
     *
     * @return the value of mx_activities_myspace_data.describe
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.describe
     *
     * @param describe the value for mx_activities_myspace_data.describe
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.create_date
     *
     * @return the value of mx_activities_myspace_data.create_date
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.create_date
     *
     * @param create_date the value for mx_activities_myspace_data.create_date
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.Update_date
     *
     * @return the value of mx_activities_myspace_data.Update_date
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.Update_date
     *
     * @param update_date the value for mx_activities_myspace_data.Update_date
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.others
     *
     * @return the value of mx_activities_myspace_data.others
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.others
     *
     * @param others the value for mx_activities_myspace_data.others
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.upperLimit
     *
     * @return the value of mx_activities_myspace_data.upperLimit
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public Integer getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.upperLimit
     *
     * @param upperLimit the value for mx_activities_myspace_data.upperLimit
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setUpperLimit(Integer upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.lowerLimit
     *
     * @return the value of mx_activities_myspace_data.lowerLimit
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public Integer getLowerLimit() {
        return lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.lowerLimit
     *
     * @param lowerLimit the value for mx_activities_myspace_data.lowerLimit
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setLowerLimit(Integer lowerLimit) {
        this.lowerLimit = lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.state
     *
     * @return the value of mx_activities_myspace_data.state
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.state
     *
     * @param state the value for mx_activities_myspace_data.state
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.cover_image_url
     *
     * @return the value of mx_activities_myspace_data.cover_image_url
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public String getCover_image_url() {
        return cover_image_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.cover_image_url
     *
     * @param cover_image_url the value for mx_activities_myspace_data.cover_image_url
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setCover_image_url(String cover_image_url) {
        this.cover_image_url = cover_image_url == null ? null : cover_image_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_data.myspace_name
     *
     * @return the value of mx_activities_myspace_data.myspace_name
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public String getMyspace_name() {
        return myspace_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_data.myspace_name
     *
     * @param myspace_name the value for mx_activities_myspace_data.myspace_name
     *
     * @mbg.generated Fri Dec 15 23:20:27 CST 2017
     */
    public void setMyspace_name(String myspace_name) {
        this.myspace_name = myspace_name == null ? null : myspace_name.trim();
    }
}