package com.weixin.ssm.model.entity;

import java.util.Date;

public class MxActivitiesMyspaceMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.material_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private Integer material_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.submit_user_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private Integer submit_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private Integer myspace_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.material_type
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private Integer material_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.create_date
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.others
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private String others;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.material_id
     *
     * @return the value of mx_activities_myspace_material.material_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public Integer getMaterial_id() {
        return material_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.material_id
     *
     * @param material_id the value for mx_activities_myspace_material.material_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setMaterial_id(Integer material_id) {
        this.material_id = material_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.submit_user_id
     *
     * @return the value of mx_activities_myspace_material.submit_user_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public Integer getSubmit_user_id() {
        return submit_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.submit_user_id
     *
     * @param submit_user_id the value for mx_activities_myspace_material.submit_user_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setSubmit_user_id(Integer submit_user_id) {
        this.submit_user_id = submit_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.myspace_id
     *
     * @return the value of mx_activities_myspace_material.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public Integer getMyspace_id() {
        return myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.myspace_id
     *
     * @param myspace_id the value for mx_activities_myspace_material.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setMyspace_id(Integer myspace_id) {
        this.myspace_id = myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.material_type
     *
     * @return the value of mx_activities_myspace_material.material_type
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public Integer getMaterial_type() {
        return material_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.material_type
     *
     * @param material_type the value for mx_activities_myspace_material.material_type
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setMaterial_type(Integer material_type) {
        this.material_type = material_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.create_date
     *
     * @return the value of mx_activities_myspace_material.create_date
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.create_date
     *
     * @param create_date the value for mx_activities_myspace_material.create_date
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.others
     *
     * @return the value of mx_activities_myspace_material.others
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.others
     *
     * @param others the value for mx_activities_myspace_material.others
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }
}