package com.weixin.ssm.model.entity;

public class MxActivitiesMyspaceCommentWithBLOBs extends MxActivitiesMyspaceComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.Comment_txt
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    private String comment_txt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.praise_user_ids
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    private String praise_user_ids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.Comment_txt
     *
     * @return the value of mx_activities_myspace_comment.Comment_txt
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    public String getComment_txt() {
        return comment_txt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.Comment_txt
     *
     * @param comment_txt the value for mx_activities_myspace_comment.Comment_txt
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    public void setComment_txt(String comment_txt) {
        this.comment_txt = comment_txt == null ? null : comment_txt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.praise_user_ids
     *
     * @return the value of mx_activities_myspace_comment.praise_user_ids
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    public String getPraise_user_ids() {
        return praise_user_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.praise_user_ids
     *
     * @param praise_user_ids the value for mx_activities_myspace_comment.praise_user_ids
     *
     * @mbg.generated Fri Dec 15 23:19:16 CST 2017
     */
    public void setPraise_user_ids(String praise_user_ids) {
        this.praise_user_ids = praise_user_ids == null ? null : praise_user_ids.trim();
    }
}