package com.weixin.ssm.model.entity;

import java.util.Date;

public class MxActivitiesMyspaceComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.comment_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private Integer comment_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private Integer myspace_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.submit_userID
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private Integer submit_userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.state
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.praise_clickNum
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private Integer praise_clickNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.create_date
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.others
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_comment.parent_comment_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    private Integer parent_comment_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.comment_id
     *
     * @return the value of mx_activities_myspace_comment.comment_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public Integer getComment_id() {
        return comment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.comment_id
     *
     * @param comment_id the value for mx_activities_myspace_comment.comment_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setComment_id(Integer comment_id) {
        this.comment_id = comment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.myspace_id
     *
     * @return the value of mx_activities_myspace_comment.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public Integer getMyspace_id() {
        return myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.myspace_id
     *
     * @param myspace_id the value for mx_activities_myspace_comment.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setMyspace_id(Integer myspace_id) {
        this.myspace_id = myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.submit_userID
     *
     * @return the value of mx_activities_myspace_comment.submit_userID
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public Integer getSubmit_userID() {
        return submit_userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.submit_userID
     *
     * @param submit_userID the value for mx_activities_myspace_comment.submit_userID
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setSubmit_userID(Integer submit_userID) {
        this.submit_userID = submit_userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.state
     *
     * @return the value of mx_activities_myspace_comment.state
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.state
     *
     * @param state the value for mx_activities_myspace_comment.state
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.praise_clickNum
     *
     * @return the value of mx_activities_myspace_comment.praise_clickNum
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public Integer getPraise_clickNum() {
        return praise_clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.praise_clickNum
     *
     * @param praise_clickNum the value for mx_activities_myspace_comment.praise_clickNum
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setPraise_clickNum(Integer praise_clickNum) {
        this.praise_clickNum = praise_clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.create_date
     *
     * @return the value of mx_activities_myspace_comment.create_date
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.create_date
     *
     * @param create_date the value for mx_activities_myspace_comment.create_date
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.others
     *
     * @return the value of mx_activities_myspace_comment.others
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.others
     *
     * @param others the value for mx_activities_myspace_comment.others
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_comment.parent_comment_id
     *
     * @return the value of mx_activities_myspace_comment.parent_comment_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public Integer getParent_comment_id() {
        return parent_comment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_comment.parent_comment_id
     *
     * @param parent_comment_id the value for mx_activities_myspace_comment.parent_comment_id
     *
     * @mbg.generated Fri Dec 15 23:19:15 CST 2017
     */
    public void setParent_comment_id(Integer parent_comment_id) {
        this.parent_comment_id = parent_comment_id;
    }
}