package com.weixin.ssm.model.entity;

import java.util.Date;

public class MxActivitiesMyspaceUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Integer myspace_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.user_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.relate_user_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Integer relate_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.create_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Date update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.state
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.others
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.remain_upload_num
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Integer remain_upload_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.img_update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Date img_update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_users.comment_update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    private Date comment_update_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.id
     *
     * @return the value of mx_activities_myspace_users.id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.id
     *
     * @param id the value for mx_activities_myspace_users.id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.myspace_id
     *
     * @return the value of mx_activities_myspace_users.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Integer getMyspace_id() {
        return myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.myspace_id
     *
     * @param myspace_id the value for mx_activities_myspace_users.myspace_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setMyspace_id(Integer myspace_id) {
        this.myspace_id = myspace_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.user_id
     *
     * @return the value of mx_activities_myspace_users.user_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.user_id
     *
     * @param user_id the value for mx_activities_myspace_users.user_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.relate_user_id
     *
     * @return the value of mx_activities_myspace_users.relate_user_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Integer getRelate_user_id() {
        return relate_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.relate_user_id
     *
     * @param relate_user_id the value for mx_activities_myspace_users.relate_user_id
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setRelate_user_id(Integer relate_user_id) {
        this.relate_user_id = relate_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.create_date
     *
     * @return the value of mx_activities_myspace_users.create_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.create_date
     *
     * @param create_date the value for mx_activities_myspace_users.create_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.update_date
     *
     * @return the value of mx_activities_myspace_users.update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.update_date
     *
     * @param update_date the value for mx_activities_myspace_users.update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.state
     *
     * @return the value of mx_activities_myspace_users.state
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.state
     *
     * @param state the value for mx_activities_myspace_users.state
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.others
     *
     * @return the value of mx_activities_myspace_users.others
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.others
     *
     * @param others the value for mx_activities_myspace_users.others
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.remain_upload_num
     *
     * @return the value of mx_activities_myspace_users.remain_upload_num
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Integer getRemain_upload_num() {
        return remain_upload_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.remain_upload_num
     *
     * @param remain_upload_num the value for mx_activities_myspace_users.remain_upload_num
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setRemain_upload_num(Integer remain_upload_num) {
        this.remain_upload_num = remain_upload_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.img_update_date
     *
     * @return the value of mx_activities_myspace_users.img_update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Date getImg_update_date() {
        return img_update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.img_update_date
     *
     * @param img_update_date the value for mx_activities_myspace_users.img_update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setImg_update_date(Date img_update_date) {
        this.img_update_date = img_update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_users.comment_update_date
     *
     * @return the value of mx_activities_myspace_users.comment_update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public Date getComment_update_date() {
        return comment_update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_users.comment_update_date
     *
     * @param comment_update_date the value for mx_activities_myspace_users.comment_update_date
     *
     * @mbg.generated Fri Dec 15 23:21:38 CST 2017
     */
    public void setComment_update_date(Date comment_update_date) {
        this.comment_update_date = comment_update_date;
    }
}