package com.weixin.ssm.model.entity;

public class MxActivitiesMyspaceMaterialWithBLOBs extends MxActivitiesMyspaceMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.load_url
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private String load_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.describe
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_activities_myspace_material.preview_img_url
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    private String preview_img_url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.load_url
     *
     * @return the value of mx_activities_myspace_material.load_url
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public String getLoad_url() {
        return load_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.load_url
     *
     * @param load_url the value for mx_activities_myspace_material.load_url
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setLoad_url(String load_url) {
        this.load_url = load_url == null ? null : load_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.describe
     *
     * @return the value of mx_activities_myspace_material.describe
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.describe
     *
     * @param describe the value for mx_activities_myspace_material.describe
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_activities_myspace_material.preview_img_url
     *
     * @return the value of mx_activities_myspace_material.preview_img_url
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public String getPreview_img_url() {
        return preview_img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_activities_myspace_material.preview_img_url
     *
     * @param preview_img_url the value for mx_activities_myspace_material.preview_img_url
     *
     * @mbg.generated Fri Dec 15 23:21:03 CST 2017
     */
    public void setPreview_img_url(String preview_img_url) {
        this.preview_img_url = preview_img_url == null ? null : preview_img_url.trim();
    }
}