package com.weixin.ssm.model.entity;

import java.util.Date;

public class MxUsersData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_id
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_name
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.password
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_typeID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer user_typeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.weixin_openID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String weixin_openID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.weixin_nikeName
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String weixin_nikeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.subscribe_time
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Date subscribe_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.weixin_remark
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String weixin_remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_sex
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer user_sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.weixin_groupid
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String weixin_groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.weixin_tagid_list
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String weixin_tagid_list;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_age
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer user_age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_schoolID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer user_schoolID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_email
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_phoneNum
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.reporter_teamID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer reporter_teamID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_state
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer user_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_regionID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Integer user_regionID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_addr
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.last_loginTime
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private Date last_loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.others
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_realName
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_idcard_num
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_idcard_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_qq_num
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_qq_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_id
     *
     * @return the value of mx_users_data.user_id
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_id
     *
     * @param user_id the value for mx_users_data.user_id
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_name
     *
     * @return the value of mx_users_data.user_name
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_name
     *
     * @param user_name the value for mx_users_data.user_name
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.password
     *
     * @return the value of mx_users_data.password
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.password
     *
     * @param password the value for mx_users_data.password
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_typeID
     *
     * @return the value of mx_users_data.user_typeID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getUser_typeID() {
        return user_typeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_typeID
     *
     * @param user_typeID the value for mx_users_data.user_typeID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_typeID(Integer user_typeID) {
        this.user_typeID = user_typeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.weixin_openID
     *
     * @return the value of mx_users_data.weixin_openID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getWeixin_openID() {
        return weixin_openID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.weixin_openID
     *
     * @param weixin_openID the value for mx_users_data.weixin_openID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setWeixin_openID(String weixin_openID) {
        this.weixin_openID = weixin_openID == null ? null : weixin_openID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.weixin_nikeName
     *
     * @return the value of mx_users_data.weixin_nikeName
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getWeixin_nikeName() {
        return weixin_nikeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.weixin_nikeName
     *
     * @param weixin_nikeName the value for mx_users_data.weixin_nikeName
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setWeixin_nikeName(String weixin_nikeName) {
        this.weixin_nikeName = weixin_nikeName == null ? null : weixin_nikeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.subscribe_time
     *
     * @return the value of mx_users_data.subscribe_time
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Date getSubscribe_time() {
        return subscribe_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.subscribe_time
     *
     * @param subscribe_time the value for mx_users_data.subscribe_time
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setSubscribe_time(Date subscribe_time) {
        this.subscribe_time = subscribe_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.weixin_remark
     *
     * @return the value of mx_users_data.weixin_remark
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getWeixin_remark() {
        return weixin_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.weixin_remark
     *
     * @param weixin_remark the value for mx_users_data.weixin_remark
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setWeixin_remark(String weixin_remark) {
        this.weixin_remark = weixin_remark == null ? null : weixin_remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_sex
     *
     * @return the value of mx_users_data.user_sex
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getUser_sex() {
        return user_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_sex
     *
     * @param user_sex the value for mx_users_data.user_sex
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_sex(Integer user_sex) {
        this.user_sex = user_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.weixin_groupid
     *
     * @return the value of mx_users_data.weixin_groupid
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getWeixin_groupid() {
        return weixin_groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.weixin_groupid
     *
     * @param weixin_groupid the value for mx_users_data.weixin_groupid
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setWeixin_groupid(String weixin_groupid) {
        this.weixin_groupid = weixin_groupid == null ? null : weixin_groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.weixin_tagid_list
     *
     * @return the value of mx_users_data.weixin_tagid_list
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getWeixin_tagid_list() {
        return weixin_tagid_list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.weixin_tagid_list
     *
     * @param weixin_tagid_list the value for mx_users_data.weixin_tagid_list
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setWeixin_tagid_list(String weixin_tagid_list) {
        this.weixin_tagid_list = weixin_tagid_list == null ? null : weixin_tagid_list.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_age
     *
     * @return the value of mx_users_data.user_age
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getUser_age() {
        return user_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_age
     *
     * @param user_age the value for mx_users_data.user_age
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_age(Integer user_age) {
        this.user_age = user_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_schoolID
     *
     * @return the value of mx_users_data.user_schoolID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getUser_schoolID() {
        return user_schoolID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_schoolID
     *
     * @param user_schoolID the value for mx_users_data.user_schoolID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_schoolID(Integer user_schoolID) {
        this.user_schoolID = user_schoolID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_email
     *
     * @return the value of mx_users_data.user_email
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_email() {
        return user_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_email
     *
     * @param user_email the value for mx_users_data.user_email
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_email(String user_email) {
        this.user_email = user_email == null ? null : user_email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_phoneNum
     *
     * @return the value of mx_users_data.user_phoneNum
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_phoneNum() {
        return user_phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_phoneNum
     *
     * @param user_phoneNum the value for mx_users_data.user_phoneNum
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_phoneNum(String user_phoneNum) {
        this.user_phoneNum = user_phoneNum == null ? null : user_phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.reporter_teamID
     *
     * @return the value of mx_users_data.reporter_teamID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getReporter_teamID() {
        return reporter_teamID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.reporter_teamID
     *
     * @param reporter_teamID the value for mx_users_data.reporter_teamID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setReporter_teamID(Integer reporter_teamID) {
        this.reporter_teamID = reporter_teamID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_state
     *
     * @return the value of mx_users_data.user_state
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getUser_state() {
        return user_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_state
     *
     * @param user_state the value for mx_users_data.user_state
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_state(Integer user_state) {
        this.user_state = user_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_regionID
     *
     * @return the value of mx_users_data.user_regionID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Integer getUser_regionID() {
        return user_regionID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_regionID
     *
     * @param user_regionID the value for mx_users_data.user_regionID
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_regionID(Integer user_regionID) {
        this.user_regionID = user_regionID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_addr
     *
     * @return the value of mx_users_data.user_addr
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_addr() {
        return user_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_addr
     *
     * @param user_addr the value for mx_users_data.user_addr
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_addr(String user_addr) {
        this.user_addr = user_addr == null ? null : user_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.last_loginTime
     *
     * @return the value of mx_users_data.last_loginTime
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public Date getLast_loginTime() {
        return last_loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.last_loginTime
     *
     * @param last_loginTime the value for mx_users_data.last_loginTime
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setLast_loginTime(Date last_loginTime) {
        this.last_loginTime = last_loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.others
     *
     * @return the value of mx_users_data.others
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.others
     *
     * @param others the value for mx_users_data.others
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_realName
     *
     * @return the value of mx_users_data.user_realName
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_realName() {
        return user_realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_realName
     *
     * @param user_realName the value for mx_users_data.user_realName
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_realName(String user_realName) {
        this.user_realName = user_realName == null ? null : user_realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_idcard_num
     *
     * @return the value of mx_users_data.user_idcard_num
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_idcard_num() {
        return user_idcard_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_idcard_num
     *
     * @param user_idcard_num the value for mx_users_data.user_idcard_num
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_idcard_num(String user_idcard_num) {
        this.user_idcard_num = user_idcard_num == null ? null : user_idcard_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_qq_num
     *
     * @return the value of mx_users_data.user_qq_num
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_qq_num() {
        return user_qq_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_qq_num
     *
     * @param user_qq_num the value for mx_users_data.user_qq_num
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_qq_num(String user_qq_num) {
        this.user_qq_num = user_qq_num == null ? null : user_qq_num.trim();
    }
}