package com.weixin.ssm.model.entity;

public class MxUsersDataWithBLOBs extends MxUsersData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.weixin_headUrl
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String weixin_headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mx_users_data.user_tags
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    private String user_tags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.weixin_headUrl
     *
     * @return the value of mx_users_data.weixin_headUrl
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getWeixin_headUrl() {
        return weixin_headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.weixin_headUrl
     *
     * @param weixin_headUrl the value for mx_users_data.weixin_headUrl
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setWeixin_headUrl(String weixin_headUrl) {
        this.weixin_headUrl = weixin_headUrl == null ? null : weixin_headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mx_users_data.user_tags
     *
     * @return the value of mx_users_data.user_tags
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public String getUser_tags() {
        return user_tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mx_users_data.user_tags
     *
     * @param user_tags the value for mx_users_data.user_tags
     *
     * @mbg.generated Fri Dec 15 22:52:32 CST 2017
     */
    public void setUser_tags(String user_tags) {
        this.user_tags = user_tags == null ? null : user_tags.trim();
    }
}